[package]
name = "km_common"
version = "0.1.0"
edition = "2024"

[dependencies]

prost = "0.13"
zeroize = { version = "1.8.2", features = ["derive"] }
libc = "0.2.182"
thiserror = "2.0"
clear_on_drop = "0.2"
bssl-crypto = { path = "../third_party/bssl-crypto" }
memmap2 = "0.9.9"
uuid = { version = "1.20.0", features = ["v4"] }

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3.2.0"

[dev-dependencies]
hex = "0.4"
