import requests
import requests_unixsocket
import json
import base64
import os
import time
import re
from urllib.parse import quote
from pyhpke import CipherSuite, KDFId, AEADId, KEMId

session = requests_unixsocket.Session()
socket_path = "/tmp/wsd.sock"
base_url = f"http+unix://{quote(socket_path, safe='')}"

# Check for server.log generated by background WSD server
LOG_FILE = "server.log"

def get_public_key():
    print("\n--- Waiting for Public Key from server.log ---")
    for _ in range(50):
        if os.path.exists(LOG_FILE):
            with open(LOG_FILE, "r") as f:
                content = f.read()
                match = re.search(r"Generated KEM Public Key \(base64\): ([\w+/=]+)", content)
                if match:
                    print(f"Found Public Key: {match.group(1)}")
                    return match.group(1)
        time.sleep(0.1)
    raise TimeoutError("Failed to find public key in server.log")

def generate_key():
    print("\n--- Generating Key ---")
    payload = {
        "algorithm": "DHKEM_X25519_HKDF_SHA256",
        "key_protection_mechanism": "KEY_PROTECTION_VM",
        "lifespan": 3600
    }
    resp = session.post(f"{base_url}/v1/keys:generate_kem", json=payload)
    if resp.status_code != 200:
        print(f"Error: {resp.status_code} - {resp.text}")
    resp.raise_for_status()
    key_handle = resp.json()["key_handle"]
    print(f"Generated Key: {key_handle['handle']}")
    return key_handle

def get_capabilities():
    print("\n--- Getting Capabilities ---")
    resp = session.get(f"{base_url}/v1/capabilities")
    if resp.status_code != 200:
        print(f"Error: {resp.status_code} - {resp.text}")
    resp.raise_for_status()
    caps = resp.json()
    print(f"Capabilities:\n{json.dumps(caps, indent=2)}")
    return caps

def do_encap(pub_key_b64):
    print("\n--- Performing HPKE Encapsulation ---")
    pub_key_bytes = base64.b64decode(pub_key_b64)
    suite = CipherSuite.new(KEMId.DHKEM_X25519_HKDF_SHA256, KDFId.HKDF_SHA256, AEADId.AES256_GCM)
    kem_pub_key = suite.kem.deserialize_public_key(pub_key_bytes)
    # The Go test (server_test.go) uses an empty AAD for the public encapsulation test
    # but the KPS protocol includes an AAD. Let's send an empty info for encap, 
    # as the protocol's AAD is applied to the encapsulation ciphertext, not the KEM itself. 
    # Actually HPKE requires info for encap? The go client in Vanguard passes empty info to HPKE SetupBaseI.
    enc, sender_context = suite.create_sender_context(kem_pub_key, b"")
    
    # Let's encrypt a dummy plaintext
    plaintext = b"authentic-secret-32-bytes-value!" # 32 bytes
    ciphertext = sender_context.seal(b"", plaintext)
    
    # We must send the `enc` (encapsulated key) to the `decap` endpoint
    # wait, the API decap takes `ciphertext` which maps to the "encapsulated_key".
    # In HPKE, decap produces the shared secret, we don't send the ciphertext sealed with AEAD,
    # we just send the encapsulated key (`enc`), and the server retrieves the shared_secret.
    # WSD's Decap API is just a KEM Decap. It doesn't decrypt the AEAD ciphertext.
    # The server performs Decap returning the KEM shared secret.
    return enc

def decap_key(key_handle, enc_bytes):
    print(f"\n--- Decapping Key {key_handle['handle']} ---")
    enc_b64 = base64.b64encode(enc_bytes).decode('utf-8')
    payload = {
        "key_handle": key_handle,
        "ciphertext": {
            "algorithm": "DHKEM_X25519_HKDF_SHA256",
            "ciphertext": enc_b64
        }
    }
    resp = session.post(f"{base_url}/v1/keys:decap", json=payload)
    if resp.status_code != 200:
        print(f"Error: {resp.status_code} - {resp.text}")
    resp.raise_for_status()
    decap = resp.json()["shared_secret"]
    print(f"Decapped shared secret: {json.dumps(decap, indent=2)}")
    return decap

if __name__ == "__main__":
    try:
        get_capabilities()
        handle = generate_key()
        pub_key_b64 = get_public_key()
        enc_bytes = do_encap(pub_key_b64)
        decap_key(handle, enc_bytes)
        print("\nSuccess! Flow completed.")
    except Exception as e:
        print(f"An error occurred: {e}")
